### ISSUE TITLE
Graphical installer fails LUKS encrypted installation

### ISSUE THREAD

**Issue by onny** [NixOS/calamares-nixos-extensions#35]
### Describe the bug

Graphical installer fails LUKS encrypted installation in Qemu environemt (BIOS, 6 GB memory, 20GB storage)

Tried 23.11 and 24.05-beta release with Gnome (installed without UI)

### Steps To Reproduce
1.
![image](https://github.com/NixOS/nixpkgs/assets/757752/0c6f4fa4-64fb-4504-9fe5-1a787a098738)

2.
![image](https://github.com/NixOS/nixpkgs/assets/757752/b475fa13-282d-4eae-8622-544d3f7ebd58)

3.
![image](https://github.com/NixOS/nixpkgs/assets/757752/b4c9cf65-dbf3-48c7-b5c4-8e2beb7912b7)

4. Start installation, it will fail probably at the final stage
![image](https://github.com/NixOS/nixpkgs/assets/757752/dcdd1875-76f9-4072-91fc-286d88165c63)

### Expected behavior

Installation should succeed on LUKS encrypted partition

### Additional context

```
2024-05-24 - 18:37:26 [6]: [PYTHON JOB]: "nixos-install: /nix/store/bylm45pik44qjqq436xc7nf8610fvn0d-lndir-1.0.5/bin/lndir: line 1: syntax error near unexpected token `)'" 
2024-05-24 - 18:37:26 [6]: virtual void Calamares::JobThread::run()
2024-05-24 - 18:37:26 [6]:     Skipping non-emergency job "Set password for user onny" 
2024-05-24 - 18:37:26 [6]:     ..  Skipping non-emergency job "Set password for user root" 
2024-05-24 - 18:37:26 [6]:     ..  Skipping non-emergency job "Unmounting file systems…" 
2024-05-24 - 18:37:26 [1]: void Calamares::ViewManager::onInstallationFailed(const QString&, const QString&)
2024-05-24 - 18:37:26 [1]:     ERROR: Installation failed: "nixos-install failed" 
2024-05-24 - 18:37:26 [6]:     .. - message: "nixos-install failed" 
2024-05-24 - 18:37:26 [6]:     .. - details: Installation failed to complete
2024-05-24 - 18:37:29 [6]: void Calamares::ViewManager::onInstallationFailed(const QString&, const QString&)
2024-05-24 - 18:37:29 [6]:     Calamares will quit when the dialog closes. 
2024-05-24 - 18:37:29 [6]: DEBUG (Qt): QML Component (default slideshow) deactivated
2024-05-24 - 18:37:29 [6]: void Config::doNotify(bool, bool)
2024-05-24 - 18:37:29 [6]:     Sending notification of completion: failed 
```

Error log https://termbin.com/gfp8

Error log from an other installation attempt

```
copying path '/nix/store/9rsjf81qyls5d76bcv84awnl3lr7cwh9-libnice-0.1.22' to 'local'...
firmware for /nix/store/3fqx5q8j95avdqhb8cbic7iqwdfx3hgn-linux-6.6.31-modules/lib/modules/6.6.31/kernel/drivers/usb/host/xhci-pci.ko.xz: renesas_usb_fw.mem
lib/firmware -> /nix/store/pbg9m9qb02545hrk1m29mhgcsl3ixc9h-linux-6.6.31-modules-shrunk/lib/firmware
WARNING: missing firmware renesas_usb_fw.mem for module /nix/store/3fqx5q8j95avdqhb8cbic7iqwdfx3hgn-linux-6.6.31-modules/lib/modules/6.6.31/kernel/drivers/usb/host/xhci-pci.ko.xz
Traceback (most recent call last):
  File "/nix/store/pllbh8x6i4zgkkxpz7n0zdk9f9yz1p6m-nixos-render-docs-0.0/bin/.nixos-render-docs-wrapped", line 6, in <module>
    from nixos_render_docs import main
  File "/nix/store/pllbh8x6i4zgkkxpz7n0zdk9f9yz1p6m-nixos-render-docs-0.0/lib/python3.11/site-packages/nixos_render_docs/__init__.py", line 8, in <module>
    from . import manual
  File "/nix/store/pllbh8x6i4zgkkxpz7n0zdk9f9yz1p6m-nixos-render-docs-0.0/lib/python3.11/site-packages/nixos_render_docs/manual.py", line 13, in <module>
    from markdown_it.token import Token
  File "/nix/store/iq08ij2qrjq187y3bkkzvrp6i84kx4r9-python3.11-markdown-it-py-3.0.0/lib/python3.11/site-packages/markdown_it/__init__.py", line 5, in <module>
    from .main import MarkdownIt
  File "/nix/store/iq08ij2qrjq187y3bkkzvrp6i84kx4r9-python3.11-markdown-it-py-3.0.0/lib/python3.11/site-packages/markdown_it/main.py", line 1, in <module>
    from __future__ import annotations
SyntaxError: source code string cannot contain null bytes
error: builder for '/nix/store/9dz7pfvk5bjyqjbalsckyr7dd6nbvynf-nixos-manual-html.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/lsa529vlalnff1lk3aargvg5var19ljh-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/m5gb1cw8p85fiq5y26jjpzwlxhg6krwl-nixos-system-nixos-24.05beta5.1a7abfa62e8a.drv' failed to build
```

### Notify maintainers

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by onny** [comment]
@davidak

**Comment by Readf0x** [comment]
Same here, I chose manual partitioning and it fails upon trying to create an encrypted partition.

https://termbin.com/hy6y

**Comment by ElvishJerricco** [comment]
The original issue appears to be some kind of problem with building the NixOS manual. Which is pretty surprising, but has nothing to do with encryption.

@Readf0x Your log indicates that cryptsetup is failing to make the encrypted partition somehow, but the calamares logs aren't showing whatever error message it gave... Regardless, it's a separate problem from @onny's.

**Comment by ElvishJerricco** [comment]
This repo has been merged upstream into nixpkgs and will be archived. If this is still an issue, please open a new one there.
